#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
polybar &
picom &
xwallpaper --zoom ~/Pictures/Walls/thiemeyer_road_to_samarkand.jpg &
gentoo-pipewire-launcher &
wireplumber &
mpd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap           26
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
